[package]
name = "s3-proxy-rs"
version = "1.0.11"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
axum = "0.8.4"
aws-sdk-s3 = "1.100.0"
aws-config = "1.8.3"
dotenv = "0.15.0"
mime_guess = "2.0.5"
path-clean = "1.0.1"
thiserror = "2.0.12"
