version: '3.8'

services:
  s3-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./s3-proxy-rs/.env
    restart: unless-stopped
    container_name: s3-proxy

